### ISSUE TITLE
Add smiles-to-3d and vsflow code into repo

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/3d-analogues#2]
Merge the relevant code from
https://github.com/ersilia-os/vsflow-ligand-based-3d-screening
https://github.com/ersilia-os/smiles-to-3d

into this repository if we prefer easiness of editing

**Comment by GemmaTuron** [comment]
We have decided to incorporate only VSFlow and leave the smiles-3d as an independent repo. 
I need:

- [x] Confirmation from @ankitskvmdam and @miquelduranfrigola if these repositories are used somewhere else. If so, I've changed the structure a bit so we might need to do some changes - can you point me to where it is being applied?
- [x] Make sure the smiles-3d is pip installable - see #1 
- [x] Would be nice to make sure this runs on Mac. At the moment, I am unable to install cdpkit on a Mac

**Comment by miquelduranfrigola** [comment]
Thanks @GemmaTuron 

As for installation on Mac, I assume you followed these instructions? https://cdpkit.org/v1.1.1/installation.html

**Comment by GemmaTuron** [comment]
I am simply pip installing it from PyPi
I can try installing from GitHub

**Comment by GemmaTuron** [comment]
ok, bug found.
CDPKit only has wheels for MacOS Sonoma (14.0) - I updated my Mac and worked without problems!

I will incorporate the vsflow code into the 3d-analogues repository and archive the vsflow repo so we do not get confused, if that sounds good @miquelduranfrigola ?
I will not touch the smiles-to-3d.

@ankitskvmdam you can have a look at this repo. I can make the docking optional so we have a quick way of scoring molecules for docking, vsflow or both (related to: https://github.com/ersilia-os/ersilia/issues/1128)

**Comment by miquelduranfrigola** [comment]
Thanks @GemmaTuron this makes a lot of sense. Good that we found the issue. Perhaps we need to put this information in the README?

**Comment by GemmaTuron** [comment]
After giving it some thought I've decided to leave this repo as is, with the necessary files from vsflow incorporated.
At this moment, the repository is only useful to do Docking AND 3dShape similarity, as both are intertwined (docking is used to get the best conformers for 3D Shape similarity).

If the user wishes to do only 3DShape similarity they can still use the vsflow-ligand-based-3d-screening repository.

I'll close this issue
